sonar.projectKey=inventory-frontend
sonar.projectName=Inventory Frontend
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**,**/*.js.map
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/inventory-frontend/lcov.info
